// Hairstyle catalog — each style encoded as an attribute vector so face-shape
// harmony can be COMPUTED, not hand-enumerated (visagism-domain.md §5.3).
// Seed set of 28 styles covering masculine/feminine conventions and textures
// 1A–4C. Grow toward 60–100 with the same schema.

import type { Archetype, ArchetypeVector, HairStyle } from "./types";

const arch = (v: Partial<ArchetypeVector>): ArchetypeVector => ({
  ousado: 0,
  criativo: 0,
  acolhedor: 0,
  profissional: 0,
  elegante: 0,
  romantico: 0,
  sereno: 0,
  ...v,
});

export const CATALOG: HairStyle[] = [
  // ---------------- Masculine ----------------
  {
    id: "pompadour_fade",
    name: "Pompadour with fade",
    namePt: "Pompadour com fade",
    description:
      "Volume alto no topo penteado para trás, laterais em degradê curto.",
    convention: "masculina",
    lengthBand: "curto",
    silhouette: { temples: -1, cheeks: -1, jaw: 0, crownHeight: 2 },
    line: { straightness: 1, curvature: 1, diagonality: 1, angularity: 1 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["1B", "1C", "2A", "2B"],
    textureVia: { escova: ["2C", "3A"] },
    densityMin: "media",
    maintenanceMinutes: 15,
    salonWeeks: 4,
    archetypes: arch({ ousado: 0.8, profissional: 0.7, elegante: 0.5 }),
    renderPrompt:
      "a classic pompadour haircut with short faded sides, volume swept up and back on top",
  },
  {
    id: "textured_crop",
    name: "Textured crop",
    namePt: "Crop texturizado",
    description:
      "Topo curto e texturizado com franja reta para a frente, laterais baixas.",
    convention: "masculina",
    lengthBand: "curto",
    silhouette: { temples: 1, cheeks: 0, jaw: 0, crownHeight: 0 },
    line: { straightness: 0, curvature: 0, diagonality: 2, angularity: 1 },
    fringe: "texturizada",
    foreheadCoverage: "parcial",
    textureNative: ["1B", "1C", "2A", "2B", "2C", "3A"],
    textureVia: {},
    densityMin: "baixa",
    maintenanceMinutes: 5,
    salonWeeks: 4,
    archetypes: arch({ criativo: 0.7, ousado: 0.4, acolhedor: 0.4 }),
    renderPrompt:
      "a modern textured crop haircut with a short forward fringe and low faded sides",
  },
  {
    id: "buzz_cut",
    name: "Buzz cut",
    namePt: "Corte máquina (buzz)",
    description: "Raspado uniforme e curto em toda a cabeça.",
    convention: "masculina",
    lengthBand: "raspado",
    silhouette: { temples: 0, cheeks: 0, jaw: 0, crownHeight: -1 },
    line: { straightness: 1, curvature: 0, diagonality: 0, angularity: 2 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: [
      "1A", "1B", "1C", "2A", "2B", "2C", "3A", "3B", "3C", "4A", "4B", "4C",
    ],
    textureVia: {},
    densityMin: "baixa",
    maintenanceMinutes: 5,
    salonWeeks: 3,
    archetypes: arch({ ousado: 0.9, profissional: 0.4, sereno: 0.3 }),
    renderPrompt: "a very short uniform buzz cut",
  },
  {
    id: "side_part_classic",
    name: "Classic side part",
    namePt: "Risca lateral clássica",
    description: "Corte social com risca lateral definida e acabamento polido.",
    convention: "masculina",
    lengthBand: "curto",
    silhouette: { temples: 0, cheeks: -1, jaw: 0, crownHeight: 1 },
    line: { straightness: 2, curvature: 0, diagonality: 1, angularity: 1 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["1A", "1B", "1C", "2A"],
    textureVia: { progressiva: ["2B", "2C"] },
    densityMin: "baixa",
    maintenanceMinutes: 5,
    salonWeeks: 4,
    archetypes: arch({ profissional: 0.9, elegante: 0.6, sereno: 0.4 }),
    renderPrompt:
      "a classic gentleman's side part haircut, neatly combed with a defined part",
  },
  {
    id: "medium_flow",
    name: "Medium flow",
    namePt: "Médio despojado (flow)",
    description:
      "Comprimento médio com movimento natural, orelhas semi-cobertas.",
    convention: "masculina",
    lengthBand: "orelha",
    silhouette: { temples: 1, cheeks: 1, jaw: 0, crownHeight: 0 },
    line: { straightness: 0, curvature: 2, diagonality: 1, angularity: -1 },
    fringe: "lateral",
    foreheadCoverage: "parcial",
    textureNative: ["1C", "2A", "2B", "2C", "3A"],
    textureVia: { permanente: ["1A", "1B"] },
    densityMin: "media",
    maintenanceMinutes: 5,
    salonWeeks: 8,
    archetypes: arch({ acolhedor: 0.7, criativo: 0.6, romantico: 0.5 }),
    renderPrompt:
      "medium-length flowing hair with natural wave and movement, ears partially covered",
  },
  {
    id: "afro_shaped",
    name: "Shaped afro",
    namePt: "Black power modelado",
    description:
      "Afro com contorno esculpido, volume equilibrado e laterais definidas.",
    convention: "neutra",
    lengthBand: "curto",
    silhouette: { temples: 1, cheeks: 1, jaw: 0, crownHeight: 2 },
    line: { straightness: 0, curvature: 2, diagonality: 0, angularity: 0 },
    fringe: "nenhuma",
    foreheadCoverage: "parcial",
    textureNative: ["4A", "4B", "4C", "3C"],
    textureVia: {},
    densityMin: "media",
    maintenanceMinutes: 15,
    salonWeeks: 4,
    archetypes: arch({ ousado: 0.7, criativo: 0.7, acolhedor: 0.4 }),
    renderPrompt:
      "a beautifully shaped natural afro with sculpted rounded silhouette and clean edges",
  },
  {
    id: "afro_high_top",
    name: "High top fade",
    namePt: "High top fade",
    description:
      "Volume vertical no topo com laterais raspadas — geometria marcante.",
    convention: "masculina",
    lengthBand: "curto",
    silhouette: { temples: 0, cheeks: -1, jaw: 0, crownHeight: 2 },
    line: { straightness: 2, curvature: 0, diagonality: 0, angularity: 2 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["4A", "4B", "4C", "3C"],
    textureVia: {},
    densityMin: "alta",
    maintenanceMinutes: 15,
    salonWeeks: 3,
    archetypes: arch({ ousado: 0.9, criativo: 0.8, profissional: 0.3 }),
    renderPrompt:
      "a high top fade haircut with tall flat coily volume on top and skin-faded sides",
  },
  {
    id: "twists_short",
    name: "Short twists",
    namePt: "Twists curtos",
    description:
      "Twists definidos no topo com laterais em degradê — textura em evidência.",
    convention: "masculina",
    lengthBand: "curto",
    silhouette: { temples: 1, cheeks: 0, jaw: 0, crownHeight: 1 },
    line: { straightness: 0, curvature: 1, diagonality: 2, angularity: 0 },
    fringe: "texturizada",
    foreheadCoverage: "parcial",
    textureNative: ["3C", "4A", "4B", "4C"],
    textureVia: {},
    densityMin: "media",
    maintenanceMinutes: 15,
    salonWeeks: 4,
    archetypes: arch({ criativo: 0.9, ousado: 0.5, acolhedor: 0.4 }),
    renderPrompt:
      "short defined two-strand twists on top with faded sides",
  },
  {
    id: "undercut_slick",
    name: "Slicked undercut",
    namePt: "Undercut alinhado",
    description:
      "Topo comprido penteado para trás, laterais raspadas com contraste forte.",
    convention: "masculina",
    lengthBand: "curto",
    silhouette: { temples: -1, cheeks: -1, jaw: 0, crownHeight: 1 },
    line: { straightness: 2, curvature: 0, diagonality: 1, angularity: 2 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["1A", "1B", "1C", "2A"],
    textureVia: { progressiva: ["2B", "2C", "3A"] },
    densityMin: "media",
    maintenanceMinutes: 15,
    salonWeeks: 4,
    archetypes: arch({ ousado: 0.9, elegante: 0.5, profissional: 0.5 }),
    renderPrompt:
      "a slicked-back undercut with long top hair combed back and disconnected shaved sides",
  },
  {
    id: "french_crop_fringe",
    name: "French crop",
    namePt: "French crop com franja",
    description:
      "Curto nas laterais, franja reta curta cobrindo parte da testa.",
    convention: "masculina",
    lengthBand: "curto",
    silhouette: { temples: 1, cheeks: 0, jaw: 0, crownHeight: -1 },
    line: { straightness: 1, curvature: 0, diagonality: 0, angularity: 1 },
    fringe: "reta",
    foreheadCoverage: "parcial",
    textureNative: ["1B", "1C", "2A", "2B"],
    textureVia: {},
    densityMin: "baixa",
    maintenanceMinutes: 5,
    salonWeeks: 5,
    archetypes: arch({ profissional: 0.6, sereno: 0.5, ousado: 0.3 }),
    renderPrompt:
      "a French crop haircut with a short straight fringe and tapered sides",
  },
  // ---------------- Feminine ----------------
  {
    id: "long_layers",
    name: "Long layers",
    namePt: "Longo em camadas",
    description:
      "Comprimento abaixo dos ombros com camadas suaves que emolduram o rosto.",
    convention: "feminina",
    lengthBand: "longo",
    silhouette: { temples: 0, cheeks: 1, jaw: 1, crownHeight: 0 },
    line: { straightness: 0, curvature: 2, diagonality: 1, angularity: -2 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["1B", "1C", "2A", "2B", "2C", "3A"],
    textureVia: { progressiva: ["3B", "3C"], permanente: ["1A"] },
    densityMin: "media",
    maintenanceMinutes: 15,
    salonWeeks: 10,
    archetypes: arch({ romantico: 0.9, acolhedor: 0.7, elegante: 0.6 }),
    renderPrompt:
      "long layered hair past the shoulders with soft face-framing layers",
  },
  {
    id: "blunt_bob",
    name: "Blunt bob",
    namePt: "Bob reto (blunt)",
    description:
      "Corte reto na altura do queixo, linha geométrica precisa.",
    convention: "feminina",
    lengthBand: "queixo",
    silhouette: { temples: 0, cheeks: 1, jaw: 2, crownHeight: 0 },
    line: { straightness: 2, curvature: -1, diagonality: 0, angularity: 2 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["1A", "1B", "1C", "2A"],
    textureVia: { progressiva: ["2B", "2C", "3A"] },
    densityMin: "baixa",
    maintenanceMinutes: 15,
    salonWeeks: 6,
    archetypes: arch({ ousado: 0.8, profissional: 0.8, elegante: 0.7 }),
    renderPrompt:
      "a sharp blunt bob haircut at chin length with a precise straight edge",
  },
  {
    id: "textured_lob",
    name: "Textured lob",
    namePt: "Long bob texturizado",
    description:
      "Bob alongado até os ombros com ondas e pontas leves.",
    convention: "feminina",
    lengthBand: "ombro",
    silhouette: { temples: 0, cheeks: 0, jaw: 2, crownHeight: 0 },
    line: { straightness: -1, curvature: 2, diagonality: 1, angularity: -1 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["2A", "2B", "2C", "3A"],
    textureVia: { permanente: ["1A", "1B", "1C"], escova: ["3B"] },
    densityMin: "baixa",
    maintenanceMinutes: 15,
    salonWeeks: 8,
    archetypes: arch({ acolhedor: 0.8, criativo: 0.5, elegante: 0.5 }),
    renderPrompt:
      "a shoulder-length textured long bob with soft waves and airy ends",
  },
  {
    id: "curtain_bangs_midi",
    name: "Midi with curtain bangs",
    namePt: "Médio com franja cortina",
    description:
      "Comprimento médio com franja cortina aberta emoldurando o rosto.",
    convention: "feminina",
    lengthBand: "ombro",
    silhouette: { temples: 1, cheeks: 1, jaw: 1, crownHeight: 0 },
    line: { straightness: 0, curvature: 2, diagonality: 1, angularity: -1 },
    fringe: "cortina",
    foreheadCoverage: "parcial",
    textureNative: ["1C", "2A", "2B", "2C"],
    textureVia: { escova: ["3A", "3B"] },
    densityMin: "media",
    maintenanceMinutes: 15,
    salonWeeks: 8,
    archetypes: arch({ romantico: 0.8, acolhedor: 0.7, criativo: 0.4 }),
    renderPrompt:
      "shoulder-length hair with parted curtain bangs framing the face",
  },
  {
    id: "pixie_textured",
    name: "Textured pixie",
    namePt: "Pixie texturizado",
    description:
      "Curto feminino com topo texturizado e nuca limpa.",
    convention: "feminina",
    lengthBand: "curto",
    silhouette: { temples: 1, cheeks: -1, jaw: -1, crownHeight: 1 },
    line: { straightness: 0, curvature: 0, diagonality: 2, angularity: 1 },
    fringe: "texturizada",
    foreheadCoverage: "parcial",
    textureNative: ["1A", "1B", "1C", "2A", "2B"],
    textureVia: {},
    densityMin: "baixa",
    maintenanceMinutes: 5,
    salonWeeks: 5,
    archetypes: arch({ ousado: 0.9, criativo: 0.8, profissional: 0.4 }),
    renderPrompt:
      "a short textured pixie cut with a soft choppy fringe and clean nape",
  },
  {
    id: "shag_modern",
    name: "Modern shag",
    namePt: "Shag moderno",
    description:
      "Camadas irregulares, franja desfiada, volume descontraído.",
    convention: "feminina",
    lengthBand: "ombro",
    silhouette: { temples: 1, cheeks: 2, jaw: 1, crownHeight: 1 },
    line: { straightness: -1, curvature: 1, diagonality: 2, angularity: 0 },
    fringe: "texturizada",
    foreheadCoverage: "parcial",
    textureNative: ["2A", "2B", "2C", "3A", "3B"],
    textureVia: { permanente: ["1B", "1C"] },
    densityMin: "media",
    maintenanceMinutes: 5,
    salonWeeks: 8,
    archetypes: arch({ criativo: 0.9, ousado: 0.6, romantico: 0.4 }),
    renderPrompt:
      "a modern shag haircut with choppy layers, wispy fringe and undone volume",
  },
  {
    id: "curly_rounded",
    name: "Rounded curly cut",
    namePt: "Corte cacheado arredondado",
    description:
      "Camadas para cachos 3A–3C que evitam o efeito pirâmide e valorizam a definição.",
    convention: "feminina",
    lengthBand: "ombro",
    silhouette: { temples: 1, cheeks: 1, jaw: 1, crownHeight: 1 },
    line: { straightness: -2, curvature: 2, diagonality: 0, angularity: -2 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["3A", "3B", "3C"],
    textureVia: { permanente: ["2B", "2C"] },
    densityMin: "media",
    maintenanceMinutes: 15,
    salonWeeks: 10,
    archetypes: arch({ acolhedor: 0.8, romantico: 0.7, criativo: 0.5 }),
    renderPrompt:
      "a rounded layered curly haircut with defined bouncy curls, no pyramid shape",
  },
  {
    id: "big_chop_coily",
    name: "Big chop / TWA",
    namePt: "Big chop (TWA)",
    description:
      "Crespo natural curtinho, contorno delicado — recomeço com identidade.",
    convention: "feminina",
    lengthBand: "curto",
    silhouette: { temples: 0, cheeks: 0, jaw: -1, crownHeight: 1 },
    line: { straightness: 0, curvature: 2, diagonality: 0, angularity: 0 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["4A", "4B", "4C"],
    textureVia: {},
    densityMin: "baixa",
    maintenanceMinutes: 5,
    salonWeeks: 6,
    archetypes: arch({ ousado: 0.8, sereno: 0.5, criativo: 0.5 }),
    renderPrompt:
      "a short natural coily TWA (teeny weeny afro) haircut with a soft rounded outline",
  },
  {
    id: "box_braids",
    name: "Box braids",
    namePt: "Box braids",
    description:
      "Tranças box braids médias, comprimento abaixo dos ombros — proteção e estilo.",
    convention: "feminina",
    lengthBand: "longo",
    silhouette: { temples: 0, cheeks: 0, jaw: 1, crownHeight: 0 },
    line: { straightness: 2, curvature: 0, diagonality: 1, angularity: 0 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["3C", "4A", "4B", "4C"],
    textureVia: {},
    densityMin: "media",
    maintenanceMinutes: 5,
    salonWeeks: 8,
    archetypes: arch({ elegante: 0.7, criativo: 0.7, ousado: 0.5 }),
    renderPrompt:
      "medium box braids falling past the shoulders, neat parts",
  },
  {
    id: "sleek_long_center",
    name: "Sleek long, center part",
    namePt: "Longo liso com risca central",
    description:
      "Liso espelhado, comprimento longo, risca ao meio — polimento máximo.",
    convention: "feminina",
    lengthBand: "longo",
    silhouette: { temples: -1, cheeks: -1, jaw: 0, crownHeight: -1 },
    line: { straightness: 2, curvature: -1, diagonality: 0, angularity: 0 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["1A", "1B", "1C"],
    textureVia: { progressiva: ["2A", "2B", "2C", "3A"] },
    densityMin: "media",
    maintenanceMinutes: 30,
    salonWeeks: 10,
    archetypes: arch({ elegante: 0.9, profissional: 0.7, ousado: 0.4 }),
    renderPrompt:
      "very long sleek straight glass hair with a precise center part",
  },
  {
    id: "asymmetric_bob",
    name: "Asymmetric bob",
    namePt: "Bob assimétrico",
    description:
      "Bob com um lado mais longo que o outro — diagonal marcante.",
    convention: "feminina",
    lengthBand: "queixo",
    silhouette: { temples: 0, cheeks: 0, jaw: 1, crownHeight: 0 },
    line: { straightness: 1, curvature: 0, diagonality: 2, angularity: 1 },
    fringe: "lateral",
    foreheadCoverage: "parcial",
    textureNative: ["1A", "1B", "1C", "2A", "2B"],
    textureVia: { progressiva: ["2C", "3A"] },
    densityMin: "baixa",
    maintenanceMinutes: 15,
    salonWeeks: 6,
    archetypes: arch({ criativo: 0.9, ousado: 0.7, elegante: 0.5 }),
    renderPrompt:
      "an asymmetric bob haircut, one side longer than the other, sharp diagonal line",
  },
  {
    id: "soft_waves_side",
    name: "Soft waves, deep side part",
    namePt: "Ondas suaves com risca lateral profunda",
    description:
      "Ondas glamourosas com risca lateral funda cobrindo parte da testa.",
    convention: "feminina",
    lengthBand: "longo",
    silhouette: { temples: 1, cheeks: 1, jaw: 1, crownHeight: 0 },
    line: { straightness: -1, curvature: 2, diagonality: 1, angularity: -2 },
    fringe: "lateral",
    foreheadCoverage: "parcial",
    textureNative: ["2A", "2B", "2C"],
    textureVia: { permanente: ["1A", "1B", "1C"], escova: ["3A", "3B"] },
    densityMin: "media",
    maintenanceMinutes: 30,
    salonWeeks: 10,
    archetypes: arch({ elegante: 0.9, romantico: 0.9, acolhedor: 0.5 }),
    renderPrompt:
      "long glamorous soft waves with a deep side part, old-hollywood inspired",
  },
  {
    id: "full_fringe_midi",
    name: "Midi with full fringe",
    namePt: "Médio com franja cheia",
    description:
      "Comprimento médio com franja reta cheia na altura das sobrancelhas.",
    convention: "feminina",
    lengthBand: "ombro",
    silhouette: { temples: 1, cheeks: 1, jaw: 0, crownHeight: -1 },
    line: { straightness: 1, curvature: 1, diagonality: 0, angularity: 0 },
    fringe: "reta",
    foreheadCoverage: "total",
    textureNative: ["1A", "1B", "1C", "2A"],
    textureVia: { progressiva: ["2B", "2C"] },
    densityMin: "media",
    maintenanceMinutes: 15,
    salonWeeks: 5,
    archetypes: arch({ criativo: 0.6, romantico: 0.6, ousado: 0.5 }),
    renderPrompt:
      "shoulder-length hair with a full straight brow-length fringe",
  },
  {
    id: "layered_curly_long",
    name: "Long layered curls",
    namePt: "Cachos longos em camadas",
    description:
      "Cachos definidos e longos com camadas que distribuem o volume.",
    convention: "feminina",
    lengthBand: "longo",
    silhouette: { temples: 1, cheeks: 1, jaw: 2, crownHeight: 1 },
    line: { straightness: -2, curvature: 2, diagonality: 1, angularity: -2 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["3A", "3B", "3C", "4A"],
    textureVia: { permanente: ["2B", "2C"] },
    densityMin: "alta",
    maintenanceMinutes: 30,
    salonWeeks: 12,
    archetypes: arch({ romantico: 0.9, acolhedor: 0.7, criativo: 0.5 }),
    renderPrompt:
      "long layered defined curls with balanced volume from roots to ends",
  },
  {
    id: "wolf_cut",
    name: "Wolf cut",
    namePt: "Wolf cut",
    description:
      "Híbrido de shag e mullet: topo volumoso, comprimento desfiado.",
    convention: "neutra",
    lengthBand: "ombro",
    silhouette: { temples: 1, cheeks: 1, jaw: 0, crownHeight: 2 },
    line: { straightness: -1, curvature: 1, diagonality: 2, angularity: 1 },
    fringe: "texturizada",
    foreheadCoverage: "parcial",
    textureNative: ["2A", "2B", "2C", "3A", "3B"],
    textureVia: { permanente: ["1B", "1C"] },
    densityMin: "media",
    maintenanceMinutes: 5,
    salonWeeks: 8,
    archetypes: arch({ criativo: 1.0, ousado: 0.8, romantico: 0.3 }),
    renderPrompt:
      "a trendy wolf cut with voluminous crown, shaggy layers and wispy ends",
  },
  {
    id: "chin_bob_side",
    name: "Side-parted chin bob",
    namePt: "Bob no queixo com risca lateral",
    description:
      "Bob clássico na altura do queixo com risca lateral e movimento suave.",
    convention: "feminina",
    lengthBand: "queixo",
    silhouette: { temples: 0, cheeks: 1, jaw: 2, crownHeight: 0 },
    line: { straightness: 0, curvature: 2, diagonality: 1, angularity: -1 },
    fringe: "lateral",
    foreheadCoverage: "parcial",
    textureNative: ["1B", "1C", "2A", "2B"],
    textureVia: { progressiva: ["2C", "3A"] },
    densityMin: "baixa",
    maintenanceMinutes: 15,
    salonWeeks: 6,
    archetypes: arch({ elegante: 0.8, profissional: 0.7, sereno: 0.5 }),
    renderPrompt:
      "a chin-length bob with a deep side part and soft inward movement",
  },
  {
    id: "tapered_coily",
    name: "Tapered coily cut",
    namePt: "Crespo tapered",
    description:
      "Crespo com laterais e nuca afinadas, volume concentrado no topo.",
    convention: "feminina",
    lengthBand: "curto",
    silhouette: { temples: 0, cheeks: -1, jaw: -1, crownHeight: 2 },
    line: { straightness: 0, curvature: 1, diagonality: 1, angularity: 1 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["4A", "4B", "4C", "3C"],
    textureVia: {},
    densityMin: "media",
    maintenanceMinutes: 15,
    salonWeeks: 5,
    archetypes: arch({ ousado: 0.8, elegante: 0.6, criativo: 0.6 }),
    renderPrompt:
      "a tapered natural coily cut with short sides and defined voluminous top",
  },
  {
    id: "long_one_length_straightish",
    name: "Long one-length",
    namePt: "Longo sem camadas",
    description:
      "Comprimento único e longo, acabamento natural com leve dobra.",
    convention: "feminina",
    lengthBand: "longo",
    silhouette: { temples: -1, cheeks: 0, jaw: 1, crownHeight: -1 },
    line: { straightness: 1, curvature: 1, diagonality: 0, angularity: -1 },
    fringe: "nenhuma",
    foreheadCoverage: "nenhuma",
    textureNative: ["1B", "1C", "2A"],
    textureVia: { progressiva: ["2B", "2C"] },
    densityMin: "alta",
    maintenanceMinutes: 15,
    salonWeeks: 12,
    archetypes: arch({ sereno: 0.8, romantico: 0.6, elegante: 0.5 }),
    renderPrompt: "long one-length hair with a natural soft bend, no layers",
  },
];

export const ARCHETYPE_LABELS_PT: Record<Archetype, string> = {
  ousado: "Ousadia",
  criativo: "Criatividade",
  acolhedor: "Acolhimento",
  profissional: "Profissionalismo",
  elegante: "Elegância",
  romantico: "Romantismo",
  sereno: "Serenidade",
};
